###########################################################
#   Cloud Multi-Container Environment
###########################################################
services:
  - type: web
    name: interviewer-canvas-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SDIP_DATABASE_URL
        fromDatabase:
          name: interviewer-postgres
          property: connectionString
      - key: SDIP_JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8000
      - key: INTERVIEWER_USER_ID
        value: user-123
      - key: INTERVIEWER_EMAIL
        value: host@example.com
      - key: INTERVIEWER_DISPLAY_NAME
        value: Interviewer

databases:
  - name: interviewer-postgres
    databaseName: interviewer_db
    user: interviewer_user
    plan: free