services:
  - type: web
    name: interviewer-canvas-dev
    runtime: image
    image:
      url: ghcr.io/SabaYahyaa/interview-canvas-share-training-dev-tools-zoomcamp:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: interviewer-postgres
          property: connectionString
      - key: DB_SCHEMA
        value: dev

  - type: web
    name: interview-canvas-app
    runtime: image
    image:
      url: ghcr.io/SabaYahyaa/interview-canvas-share-training-dev-tools-zoomcamp:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: interviewer-postgres
          property: connectionString
      - key: DB_SCHEMA
        value: public

databases:
  - name: interviewer-postgres
    databaseName: interviewer_db
    user: postgres
    plan: free