[project]
name = "interview-canvas-share-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "SabaYahyaa",email = "sabayahyaa@gmail.com"}
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)",
    "email-validator (>=2.3.0,<3.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg2-binary (>=2.9.13,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::Warning:fastapi.testclient",
    "ignore::Warning:starlette.testclient",
]

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]